---

- name: Install restic-rest
  include_tasks: install.yml
  tags: install

- name: create user and password for http auth
  include_tasks: htpasswd.yml
  with_items: '{{ restic_rest_repos }}'
  loop_control:
    label: "{{ item.path }}"
  tags: password

- name: Configure systemd services
  include_tasks: configure_systemd.yml
  tags: systemd
